# Welcome to Jekyll!
#
# About Theme
#
# Yet another theme for elegant writers with modern flat style and beautiful
# night/dark mode.
#
# Website: https://github.com/MohamedAliRashad/The-Simple-Arabic-Theme
#
# You can do anything you want, including projects for your clients, as long
# as you mention an attribution back (credit links in footer or project).
# See the LICENCE file.
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you
# use 'bundle exec jekyll serve'. If you change this file, please restart
# the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "ثيمة البسطاء" # Learn to Build
email: m.rashadnow@gmail.com
author: محمد رشاد

# # theme: owner/name --> Don't forget to remove/comment the gem-based theme option
# remote_theme: "MohamedAliRashad/The-Simple-Arabic-Theme"

# Copyright setting
# You can use any html code, currently below placeholders are available:
# * current year: {currentYear}
# * author: {author} (Value is the same as site.author)
# * copyright: (c) - ©
# * copyleft: (cleft)
# * sound recording copyright: (p) - ℗
#
# For example:
#   "Copyright (c) 2017-{currentYear} <a href="https://example.com">{author}</a>"
#   "Copyright © 2017-2021 Foobar"
#
copyright: "ﻷن الهدف من هذا التصميم هو نشر الأفكار باللغة العربية، فلا يوجد حقوق على المحتوى ويمكنك استخدامه ونشره بأي شكل ممكن."

description: >- # this means to ignore newlines until "baseurl:"
  A try to provide a good and simple theme for Arabic Content

baseurl: "/The-Simple-Arabic-Theme" # the subpath of your site, e.g. /blog
url: "https://mohamedalirashad.github.io" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "/The-Simple-Arabic-Theme/assets/images/arabic-half-moon.svg" # the favicon for your site
default_img: "/assets/images/banners/6.webp" # The image your visitors see on your home page (الرئيسية)

# Yat date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
  date_format: "%-d %b %Y"

# If you want more debug log, you can set true
# debug: true

# If you want to change the content width, you can set to another value
content_width: "1080px"

# If you don't want to enable caching in the text editor, change this to false
editor_cache: true

# If you don't want reactions on your post, change this to false
like_btn: true

# For meta-data to SEO, change to different arabic regions by changing the `EG`
locale: "ar_EG"

# Splitting the markdown editor in half for editing and previewing or not
split_editor: true

# Fonts that are supported (can be extended by copying the font names wanted from there https://fonts.google.com/?subset=arabic)
fonts:
  - Tajawal
  - Cairo
  - Noto Kufi Arabic
  - Almarai
  - El Messiri
  - Amiri
  - Reem Kufi
  - Rakkas

# You can choose a theme color
# Default theme colors as below:
# coolblack: #090a0b
# spacegrey: #353535
# snowwhite: #ffffff
#
# theme_color: snowwhite
#
# Custom color as below:
# theme_color: "#882250"

# You can choose a brand color
# Default brand colors as below:
# orangered: #ff5100
# greatgold: #f2cb05
# greenblue: #389092

# brand_color: orangered
#
# Custom color as below:
# brand_color: "#1a8e42"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is"manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
#
# night_mode: "auto"

# Code badge setting
# You can enable or disable the code badge and so on
# code_badge:
#   enabled: "true"
#   color: "#fff"
#   background_color: "#ff4e00"
#   text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.html
  - archives.html
  - categories.html
  - make_post.html
  - about.html

# Page default value
defaults:
  home:
    heading: "\n"
    subheading: ""
    banner: ""

# Banner default settings
# These banner settings are for global banner default, but you can also
# config it by the front matter for one specific post
# banner:
#   video: null             # Video banner source
#   loop: true              # Video loop
#   volume: 0               # Video volume (100% is 1.0)
#   start_at: 0             # Video start time
#   image: null             # Image banner source
#   opacity: 1.0            # Banner opacity (100% is 1.0)
#   background: "rgba(0, 0, 0, 0.8)"  # Banner background (Could be a image)
#   height: "640px"         # Banner default height
#   min_height: null        # Banner minium height
#   background: "#000"
#   height: "100vh"
#   min_height: "38vh"
#   heading_style: "font-family:'Droid Arabic Kufi'; font-size: 40px; font-weight: bold;"
#   subheading_style: "font-family:'Droid Arabic Kufi'; font-size: 20px; font-weight: bold; color: gold"

# Excerpt size setting
# excerpt_size: 350

# Pagination setting
# paginate: 5

# Disqus comments
# disqus:
#   shortname: "Your Disqus username"

# Gitment comments
# gitment:
#   username: "Your GitHub username"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"   # If you use a custom domain name

# Build settings
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM

encoding: utf-8
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
